version: "3.9"
services:
  frontend:
    image: sales-importer-frontend:latest
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - '80:80'
  backend:
    image: sales-importer:latest
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://database:5432/sales'
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: simplepassword
  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: simplepassword
      POSTGRES_DB: sales